---
abstract: 'searching and editing flat tabular files'
author:
  - 'Laurent Dami <dami AT cpan.org>'
build_requires:
  File::Temp: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Tabular
provides:
  File::Tabular:
    file: lib/File/Tabular.pm
    version: '0.73'
requires:
  Hash::Type: '1.0'
  Search::QueryParser: '0.92'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/damil/File-Tabular
version: '0.73'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
