# http://module-build.sourceforge.net/META-spec.html
name:         File-Tabular
version:      0.71
version_from: lib/File/Tabular.pm
installdirs:  site
requires:
    Hash::Type:                    1.0
    Search::QueryParser:           0.92

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
